
networks:
  redis-cluster:
    driver: bridge

services:
  master-A:
    image: redis:latest
    restart: unless-stopped
    container_name: master-A
    env_file:
      - .env
    command: redis-server --port 6379 ${CLUSTER_ARGS} --cluster-announce-ip master-A --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "8080:6379"
    networks:
      - redis-cluster

  master-B:
    image: redis:latest
    restart: unless-stopped
    container_name: master-B
    env_file:
      - .env
    command: redis-server --port 6379 ${CLUSTER_ARGS} --cluster-announce-ip master-B --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "8081:6379"
    networks:
      - redis-cluster

  master-C:
    image: redis:latest
    restart: unless-stopped
    container_name: master-C
    env_file:
      - .env
    command: redis-server --port 6379 ${CLUSTER_ARGS} --cluster-announce-ip master-C --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "8082:6379"
    networks:
      - redis-cluster

  slave-A1:
    image: redis:latest
    restart: unless-stopped
    container_name: slave-A1
    env_file:
      - .env
    command: redis-server --port 6379 ${CLUSTER_ARGS} --cluster-announce-ip slave-A1 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "8083:6379"
    networks:
      - redis-cluster

  slave-A2:
    image: redis:latest
    restart: unless-stopped
    container_name: slave-A2
    env_file:
      - .env
    command: redis-server --port 6379 ${CLUSTER_ARGS} --cluster-announce-ip slave-A2 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "8084:6379"
    networks:
      - redis-cluster

  slave-B1:
    image: redis:latest
    restart: unless-stopped
    container_name: slave-B1
    env_file:
      - .env
    command: redis-server --port 6379 ${CLUSTER_ARGS} --cluster-announce-ip slave-B1 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "8085:6379"
    networks:
      - redis-cluster

  slave-B2:
    image: redis:latest
    restart: unless-stopped
    container_name: slave-B2
    env_file:
      - .env
    command: redis-server --port 6379 ${CLUSTER_ARGS} --cluster-announce-ip slave-B2 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "8086:6379"
    networks:
      - redis-cluster

  slave-C1:
    image: redis:latest
    restart: unless-stopped
    container_name: slave-C1
    env_file:
      - .env
    command: redis-server --port 6379 ${CLUSTER_ARGS} --cluster-announce-ip slave-C1 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "8087:6379"
    networks:
      - redis-cluster

  slave-C2:
    image: redis:latest
    restart: unless-stopped
    container_name: slave-C2
    env_file:
      - .env
    command: redis-server --port 6379 ${CLUSTER_ARGS} --cluster-announce-ip slave-C2 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "8088:6379"
    networks:
      - redis-cluster

  redis-client:
    image: node:latest
    container_name: redis-client
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - redis-cluster
    depends_on:
      - master-A
      - master-B
      - master-C
    command: tail -f /dev/null